# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('active', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('addressOne', models.CharField(max_length=255)),
                ('addressTwo', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('permissionLevel', models.CharField(choices=[('U', 'USER'), ('G', 'AGENT'), ('A', 'ADMINISTRATOR')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='agentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='main.User'),
        ),
        migrations.AddField(
            model_name='images',
            name='listingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_id', to='main.Listing'),
        ),
    ]
