# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180924_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='listingId',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='agentId',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
