# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181007_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='./static/images/houses'),
        ),
    ]
