# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181007_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='agentId',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
