# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181014_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sq_footage',
            field=models.IntegerField(),
        ),
    ]
