# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181014_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sq_footage',
            field=models.IntegerField(blank=True),
        ),
    ]
