# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('S', 'Single-Family Home'), ('A', 'Apartment'), ('C', 'Condo'), ('T', 'Townhouse'), ('L', 'Land'), ('M', 'Mult-Family Home'), ('F', 'Farm/Ranch')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
