# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20181014_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='agentId',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
