# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20181014_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressOne', models.CharField(max_length=255)),
                ('addressTwo', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('price', models.CharField(max_length=255)),
                ('listing_type', models.CharField(choices=[('S', 'Single-Family Home'), ('A', 'Apartment'), ('C', 'Condo'), ('T', 'Townhouse'), ('L', 'Land'), ('M', 'Mult-Family Home'), ('F', 'Farm/Ranch')], max_length=1)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('sq_footage', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='main.User')),
            ],
        ),
    ]
