# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_num',
            new_name='phoneNum',
        ),
    ]
