# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-14 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20181014_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
