# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-21 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20181021_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
