# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20181201_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactticket',
            name='contact_type',
            field=models.CharField(choices=[('A', 'ADMIN'), ('G', 'AGENT')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
